# PakDuels Configuration

# Duel settings
duel:
  # Time in seconds for inventory countdown (players can organize their inventory)
  inventory-countdown-time: 10
  
  # Enable health indicators above players
  health-indicators: true
  
  # Arena regeneration settings
  regeneration:
    # Use FAWE for arena regeneration
    use-fawe: true
    
    # Delay before regenerating arena (in ticks, 20 ticks = 1 second)
    delay: 60

# Spawn location (where players are teleported after duels)
spawn:
  world: "world"
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

# Messages
messages:
  prefix: "&6[PakDuels] &r"
  
# Kit default rules (applied to new kits)
kit-defaults:
  natural-health-regen: true
  block-break: false
  block-place: false
  health-indicators: true
  hunger-loss: false
  item-drop: false
  item-pickup: false